name: biggis3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - affine
  - asyncssh
  - "dask[complete]"
  - dask-geopandas
  - dask-ml
  - descartes
  - findspark
  - fiona
  - folium
  - geojson
  - geopandas
  - geopy
  - h3-py
  - ipyleaflet
  - jupyter
  - matplotlib
  - mapclassify
  - numpy
  - pandas
  - pillow
  - pint
  - psycopg2
  - pyproj
  - rasterio
  - requests
  - rtree
  - s3fs
  - scikit-learn
  - scipy
  - shapely
  - yaml
  - pip
  - pip:
    - fastparquet
    - gdown
    - numba
    - pyarrow
    - python-geohash
    - smopy
    - s2
    - s2sphere
    - trackintel
