name: biggis24b
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - affine
  - asyncssh
  - "dask[complete]"
  - dask-geopandas
  - dask-ml
#  - boto3
  - descartes
  - findspark
  - fiona
  - folium
#  - gdal
#  - geoalchemy2
  - geojson
  - geopandas
  - geopy
  - h3-py
  - ipyleaflet
  - jupyter
  - matplotlib
  - mapclassify
#  - networkx
  - numpy
#  - osmnx
  - pandas
  - pillow
  - pint
  - psycopg2
  - pyproj
#  - pytest
#  - pyrosm
#  - pygeos
#  - rasterio
#  - requests
  - rtree
  - s3fs
  - scikit-learn
  - scipy
#  - seaborn
  - shapely
#  - spyder
#  - tqdm
#  - yaml
#  - flask
  - pip
  - pip:
    - fastparquet
    - gdown
    - numba
    - pyarrow
    - pydrill
    - python-geohash
    - smopy
    - s2
    - s2sphere
    - trackintel
